'use client'
import { motion } from 'framer-motion'
import Link from 'next/link'
import { ArrowLeft, FileText } from 'lucide-react'

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background overflow-hidden relative">
      <div className="fixed inset-0 bg-mesh-gradient opacity-60 pointer-events-none" />
      
      <div className="max-w-3xl mx-auto px-6 py-16 relative z-10">
        <Link href="/" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground mb-8 transition-colors">
          <ArrowLeft className="w-4 h-4" /> Back to Home
        </Link>
        
        <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="mb-12">
          <div className="w-12 h-12 rounded-xl bg-brand-500/10 border border-brand-500/20 flex items-center justify-center mb-6">
            <FileText className="w-6 h-6 text-brand-400" />
          </div>
          <h1 className="font-display font-bold text-4xl mb-3">Terms of Service</h1>
          <p className="text-muted-foreground">Last updated: June 8, 2026</p>
        </motion.div>
        
        <motion.div 
          initial={{ opacity: 0, y: 20 }} 
          animate={{ opacity: 1, y: 0 }} 
          transition={{ delay: 0.1 }}
          className="glass rounded-2xl p-8 space-y-6 text-sm text-muted-foreground leading-relaxed"
        >
          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing and using Maffa TaxAI (the "Platform"), you agree to comply with and be bound by these Terms of Service. If you do not agree, please do not use the Platform.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">2. Service Scope</h2>
            <p>
              Maffa TaxAI provides an automated assistant to calculate income tax based on the Indian Income Tax Act. We support calculations for both Old and New Tax Regimes (FY 2024-25).
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">3. User Conduct & Integrity</h2>
            <p>
              You represent that all details entered, including salary structures, investment records, and uploaded tax forms, are accurate and owned by you. Misrepresenting financial information or attempting to exploit the platform's AI functions is strictly prohibited.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">4. Limitation of Liability</h2>
            <p>
              The recommendations generated by our AI-engine are purely for comparative and optimization analysis. We do not warrant the absolute completeness of the advice for complex corporate structures. Under no circumstances will Maffa TaxAI be liable for penalties, interest, or filing errors occurred with the Income Tax Department.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">5. Subscription & Billing</h2>
            <p>
              Premium features (like unlimited custom document analyses and PDF generation) require active subscription. Subscriptions are billed on a monthly or annual basis. You can cancel your subscription at any time.
            </p>
          </section>
        </motion.div>
      </div>
    </div>
  )
}
